# Generated by Django 2.2.6 on 2019-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('assignment_document', models.FileField(upload_to='documents/')),
                ('possible_points', models.SmallIntegerField()),
                ('assignment_type', models.CharField(choices=[('I', 'Individual'), ('G', 'Group')], default=None, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=50)),
                ('lesson_sub_title', models.CharField(max_length=50)),
                ('objectives', models.TextField()),
                ('materials_needed', models.TextField()),
            ],
        ),
    ]
