# Generated by Django 2.2.6 on 2019-10-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_assignment_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Assignment'),
        ),
    ]
