# Generated by Django 2.2.6 on 2019-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='doc',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
