# Generated by Django 2.2.6 on 2019-10-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_course', models.CharField(max_length=50)),
                ('name_of_the_student', models.CharField(max_length=50)),
                ('attendace_status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default=None, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='doc',
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
