# Generated by Django 2.2.6 on 2019-11-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20191106_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_content',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
