# Generated by Django 2.2.6 on 2019-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
