# Generated by Django 2.2.6 on 2019-10-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('trainer', '0002_trainer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
