# Generated by Django 2.2.6 on 2019-10-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_trainer_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='email',
        ),
    ]
