# Generated by Django 2.2.6 on 2019-11-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_remove_trainer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
