# Generated by Django 2.2.6 on 2019-11-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20191101_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
