# Generated by Django 2.2.6 on 2019-10-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('confirmation_status', models.CharField(choices=[('CO', 'Confirmed'), ('PE', 'Pending'), ('CA', 'Cancelled')], default=None, max_length=2)),
                ('contact', models.EmailField(max_length=254)),
            ],
        ),
    ]
