# Generated by Django 2.2.6 on 2019-11-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20191101_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
