# Generated by Django 2.2.6 on 2019-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='student',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='student',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
