# Generated by Django 2.2.6 on 2019-10-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_id', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
